---

- hosts: all
  tasks:
    - name: create user
      user: name={{ username }} shell=/bin/bash createhome=yes

    - name: set authorized key
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
        state: present

    - name: add sudoers file
      shell: 'echo "{{ username }} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/{{ username }}'

    - name: allow user access by ssh
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: '^(AllowUsers.*)$'
        line: '\1 {{ username }}'